/**
 * TAROT DE LAS CRIATURAS DE HIERONYMUS BOSCH (EL BOSCO)
 * Base de datos completa de los 22 Arcanos Mayores
 * Simbolismo hermético, iconografía flamenca medieval y significados oraculares.
 */

const BOSCH_DECK = [
    {
        id: 0,
        roman: "0",
        name: "El Loco",
        title: "El Caminante del Mundo Flotante",
        latin: "Homo Viator",
        painting: "El Caminante / El Vendedor Ambulante (c. 1500)",
        realm: "peregrinacion",
        element: "Aire",
        image: "assets/cards/card_00.jpg",
        fallbackIcon: "🦯",
        quote: "«El alma vaga entre tabernas y caminos de fango, esquivando a los perros de la tentación hacia el umbral de lo desconocido.»",
        keywords: ["Viaje espiritual", "Desapego", "Riesgo sagrado", "Inocencia", "Vulnerabilidad"],
        upright: "Comienzo de una peregrinación existencial. Se te invita a dar un salto de fe despojándote de las cargas y las convenciones del mundo. Mantén la mirada atenta pero no permitas que las distracciones terrenales te desvíen de tu destino interior.",
        reversed: "Falta de dirección, imprudencia ciega o huida cobarde de los deberes. Caer presa de las provocaciones externas o quedarse paralizado en un camino sin salida moral.",
        creature_lore: "El caminante andrajoso de El Bosco cruza un paisaje decadente llevando su cesta a cuestas. Con un bastón se defiende del perro que le gruñe y vuelve la mirada atrás mientras una posada muestra el vicio humano. Es el peregrino eterno del alma entre el bien y el mal."
    },
    {
        id: 1,
        roman: "I",
        name: "El Mago",
        title: "El Prestidigitador de la Rana",
        latin: "Praestigiator",
        painting: "El Prestidigitador (c. 1502)",
        realm: "delicias",
        element: "Fuego",
        image: "assets/cards/card_01.jpg",
        fallbackIcon: "🎩",
        quote: "«Bajo la mirada fija en el cubilete, la boca exhala la ilusión y la mano cómplice hurta la bolsa del ingenuo.»",
        keywords: ["Destreza", "Ilusionismo", "Poder creador", "Fascinación", "Ingenio"],
        upright: "Posees los talentos y las herramientas para manifestar tu voluntad y transformar la materia. Capacidad de persuasión, astucia estratégica y resolución de dilemas mediante la agudeza mental.",
        reversed: "Charlatanería, manipulación sutil, estafa emocional o autoengaño. Alguien te distrae con trucos vistosos mientras te despoja de lo que realmente valoras.",
        creature_lore: "En la obra de El Bosco, el prestidigitador embauca a un espectador hipnotizado hasta el punto de hacerle expulsar una rana de la boca, símbolo de herejía y credulidad, mientras su compinche le sustrae la bolsa del cinturón."
    },
    {
        id: 2,
        roman: "II",
        name: "La Sacerdotisa",
        title: "La Cerda con Toca Notarial",
        latin: "Porca Sanctimonialis",
        painting: "El Jardín de las Delicias (Panel del Infierno)",
        realm: "infierno",
        element: "Agua",
        image: "assets/cards/card_02.jpg",
        fallbackIcon: "📜",
        quote: "«Envuelta en paños de abadesa, exige la firma que sella el testamento de la culpa eterna.»",
        keywords: ["Secreto", "Doctrina oculta", "Poder institucional", "Juicio velado", "Intuición"],
        upright: "Conocimiento reservado para quienes saben mirar bajo el velo de las apariencias. Intuición penetrante, acceso a memorias ancestrales y comprensión de las leyes invisibles que rigen los pactos.",
        reversed: "Hipocresía clerical, dogmas asfixiantes, pactos viciados con letra pequeña o traición perpetrada bajo la máscara de una autoridad respetable.",
        creature_lore: "En el Infierno de las Delicias, una cerda con toca de monja o abadesa abraza a un hombre forzándole a firmar pergaminos legales sellados con cera, personificando la corrupción eclesiástica y el secuestro del espíritu por el papeleo mundano."
    },
    {
        id: 3,
        roman: "III",
        name: "La Emperatriz",
        title: "La Dama del Cisne Cornudo",
        latin: "Domina Paradisíaca",
        painting: "El Jardín de las Delicias (Panel Central)",
        realm: "delicias",
        element: "Tierra",
        image: "assets/cards/card_03.jpg",
        fallbackIcon: "🦚",
        quote: "«La matriz de aguas cálidas engendra criaturas híbridas donde la flor y la carne danzan en comunión efímera.»",
        keywords: ["Fertilidad exuberante", "Sensualidad", "Abundancia", "Naturaleza febril", "Creación"],
        upright: "Época de cosecha creativa, gestación fructífera y goce de los sentidos. La imaginación florece sin restricciones y brotan ideas de una riqueza orgánica desbordante.",
        reversed: "Hedonismo destructivo, vanidad desmedida, asfixia por exceso de placeres materiales o desconexión con los ritmos naturales y espirituales.",
        creature_lore: "En el estanque central de las Delicias, figuras femeninas coronadas con pavos reales y frutos exóticos montan bestias fantásticas y cisnes de cornamenta vegetal, celebrando la sensualidad antes del despertar de la conciencia moral."
    },
    {
        id: 4,
        roman: "IV",
        name: "El Emperador",
        title: "El Monarca Pájaro del Trono Letrina",
        latin: "Rex Barathri",
        painting: "El Jardín de las Delicias (Panel del Infierno)",
        realm: "infierno",
        element: "Fuego",
        image: "assets/cards/card_04.jpg",
        fallbackIcon: "🦅",
        quote: "«Sentado en el trono de madera alta con un caldero por corona, devora a los hombres y los expele al pozo oscuro de la repetición.»",
        keywords: ["Autoridad implacable", "Estructura férrea", "Dominación", "Orden inflexible", "Poder terrenal"],
        upright: "Firmeza, capacidad de mando, establecimiento de límites claros y rigor estratégico. Control sobre el caos circundante y gobierno severo pero necesario de los propios recursos.",
        reversed: "Tiranía despótica, crueldad ciega, obsesión por el control y digestión implacable de los subordinados. Un poder que se devora a sí mismo y a quienes lo rodean.",
        creature_lore: "Coronado con una olla o caldero de bronce y con pies en jarras de cerámica, este demonio de cabeza aviar rapaz engulle a los condenados desnudos sentándose en una alta silla letrina desde donde los defeca hacia un abismo purificador."
    },
    {
        id: 5,
        roman: "V",
        name: "El Sumo Sacerdote",
        title: "El Pontífice del Salterio Roto",
        latin: "Hierophanta Haereticus",
        painting: "Las Tentaciones de San Antonio (Tríptico)",
        realm: "peregrinacion",
        element: "Tierra",
        image: "assets/cards/card_05.jpg",
        fallbackIcon: "📖",
        quote: "«Lee en códices apócrifos la liturgia de los desiertos y celebra la comunión de lo insólito.»",
        keywords: ["Tradición misteriosa", "Guía espiritual", "Ortodoxia vs Herejía", "Enseñanza", "Rito"],
        upright: "Búsqueda de un maestro interior o de una doctrina que devele el sentido último del sufrimiento humano. Puente entre lo terrenal y lo divino a través del estudio riguroso y la disciplina.",
        reversed: "Falso profeta, rigidez doctrinal ciega, hipocresía farisea o manipulación sectaria de la fe ajena.",
        creature_lore: "En las Tentaciones de San Antonio, sacerdotes y abades con fisonomías monstruosas celebran ritos insólitos sobre ruinas, advirtiendo sobre la corrupción sutil de las jerarquías que olvidan la compasión genuina."
    },
    {
        id: 6,
        roman: "VI",
        name: "Los Enamorados",
        title: "La Burbuja de Cristal y la Fresa",
        latin: "Amantes in Bulla",
        painting: "El Jardín de las Delicias (Panel Central)",
        realm: "delicias",
        element: "Aire",
        image: "assets/cards/card_06.jpg",
        fallbackIcon: "🍓",
        quote: "«Frágil como una pompa que flota sobre el estanque; dulce en la lengua como la fresa y efímera como el rocío del mediodía.»",
        keywords: ["Elección moral", "Atracción magnética", "Fragilidad del deseo", "Dilema", "Unión"],
        upright: "Cruce de caminos afectivo o existencial. Necesidad de reconciliar los deseos carnales con la pureza del espíritu. Unión apasionada, belleza compartida y vulnerabilidad mutua.",
        reversed: "Ilusión efímera que estalla al menor roce, obsesión erótica destructiva, traición a los propios principios por complacer a otro.",
        creature_lore: "Una pareja humana retoza dentro de una esfera de cristal translúcida unida al tallo de una flor extraña, mientras a su lado figuras cargan fresas gigantescas (madroños), símbolo bosquiano por excelencia de la fugacidad del placer humano."
    },
    {
        id: 7,
        roman: "VII",
        name: "El Carro",
        title: "El Pez Volador Acorazado",
        latin: "Currus Piscis Volans",
        painting: "Las Tentaciones de San Antonio",
        realm: "peregrinacion",
        element: "Agua",
        image: "assets/cards/card_07.jpg",
        fallbackIcon: "🐟",
        quote: "«Surca los vientos con timón de aleta y casquete de hierro, transportando a los navegantes del abismo hacia la victoria.»",
        keywords: ["Impulso audaz", "Conquista aérea", "Vehículo del alma", "Determinación", "Avance"],
        upright: "Victoria sobre los obstáculos mediante una voluntad inquebrantable. Movimiento audaz y capacidad de transitar por medios hostiles con serenidad y dominio.",
        reversed: "Pérdida de rumbo, arrogancia tecnológica o mágica, estrellarse por falta de anclaje a la realidad terrenal.",
        creature_lore: "El Bosco plasma asombrosas naves aéreas en forma de peces mecánicos y alados montados por caballeros y demonios, surcando los cielos nocturnos como alegoría de la mente que vuela más allá de sus límites naturales."
    },
    {
        id: 8,
        roman: "VIII",
        name: "La Justicia",
        title: "El Cuchillo y las Orejas Cercenadas",
        latin: "Iustitia Caecutiens",
        painting: "El Jardín de las Delicias (Panel del Infierno)",
        realm: "infierno",
        element: "Aire",
        image: "assets/cards/card_08.jpg",
        fallbackIcon: "🗡️",
        quote: "«Dos orejas colosales unidas por una hoja afilada: oír todo sin juzgar con piedad engendra la carnicería de la ley ciega.»",
        keywords: ["Equidad tajante", "Causa y efecto", "Claridad cortante", "Juicio implacable", "Verdad"],
        upright: "Resolución justa y lúcida. La espada de la verdad separa la mentira de lo genuino. Aceptación serena de las consecuencias de actos pasados y restauración del equilibrio cósmico.",
        reversed: "Juicio sesgado, condena injusta, murmuración destructiva o ensañamiento punitivo sin misericordia.",
        creature_lore: "Uno de los iconos más aterradores del Infierno bosquiano: dos orejas humanas gigantes atravesadas por una flecha sujetan entre sí una gigantesca cuchilla que aplasta a los condenados, símbolo del peligro de la murmuración y del juicio implacable."
    },
    {
        id: 9,
        roman: "IX",
        name: "El Ermitaño",
        title: "San Antonio en las Ruinas",
        latin: "Antonius Anachoreta",
        painting: "Las Tentaciones de San Antonio (c. 1501)",
        realm: "peregrinacion",
        element: "Tierra",
        image: "assets/cards/card_09.jpg",
        fallbackIcon: "🏮",
        quote: "«En medio del torbellino de monstruos y delirios, el anacoreta no mira a las bestias, sino a la llama interior de su celda.»",
        keywords: ["Introspección", "Silencio protector", "Templanza interior", "Sabiduría solitaria", "Firmeza"],
        upright: "Retiro voluntario para discernir lo verdadero en medio de la confusión social. Soledad fecunda, madurez espiritual y resistencia frente a la seducción colectiva.",
        reversed: "Aislamiento enfermizo, misantropía amarga, paranoia ante el mundo o incapacidad para recibir ayuda ajena.",
        creature_lore: "San Antonio Abad permanece imperturbable en su hábito pardo, apoyado en su cayado tau mientras monstruos alados, diablos con rostros grotescos y quimeras intentan quebrar su paz interior sin éxito."
    },
    {
        id: 10,
        roman: "X",
        name: "La Rueda de la Fortuna",
        title: "El Carro de Heno y los Demonios",
        latin: "Currus Foeni",
        painting: "El Carro de Heno (c. 1516)",
        realm: "delicias",
        element: "Fuego",
        image: "assets/cards/card_10.jpg",
        fallbackIcon: "🌾",
        quote: "«El mundo es un gran montón de heno; cada quien arranca lo que puede, y los demonios tiran de las ruedas hacia el foso.»",
        keywords: ["Ciclos ineludibles", "Giro del destino", "Ilusión de la riqueza", "Oportunidad", "Karma"],
        upright: "Cambio súbito de circunstancias. Comprensión de la naturaleza cíclica de la fortuna. Momento propicio para liberarse del apego a las ganancias materiales y subirse a la corriente correcta.",
        reversed: "Racha adversa debida a la codicia desmedida, caída de una posición de privilegio ganada con engaños, resistencia inútil al cambio.",
        creature_lore: "Inspirado en el proverbio flamenco, emperadores, papas y plebeyos se disputan un puñado de heno sobre un carro tirado por bestias demoníacas que conducen a toda la comitiva directamente al abismo."
    },
    {
        id: 11,
        roman: "XI",
        name: "La Fuerza",
        title: "El Caballero Lagarto y la Salamandra",
        latin: "Virtus Draconica",
        painting: "El Jardín de las Delicias (Panel Central)",
        realm: "delicias",
        element: "Fuego",
        image: "assets/cards/card_11.jpg",
        fallbackIcon: "🦎",
        quote: "«No se vence al reptil despedazándolo con ira, sino cabalgando su lomo con la suave brida del entendimiento.»",
        keywords: ["Dominio sereno", "Valor moral", "Integración de la sombra", "Fuerza magnética", "Paciencia"],
        upright: "Poderío interior que no necesita recurrir a la violencia. Capacidad de domesticar los impulsos primitivos y transmutar la agresividad en devoción y perseverancia.",
        reversed: "Desborde de cólera, debilidad de carácter, rendición ante los instintos destructivos o abuso de la fuerza.",
        creature_lore: "En la procesión que rodea el estanque paradisíaco, figuras humanas montan dócilmente salamandras gigantes y quimeras acorazadas, demostrando que la verdadera fuerza radica en gobernar el fuego reptiliano."
    },
    {
        id: 12,
        roman: "XII",
        name: "El Colgado",
        title: "El Mártir del Arpa Infernal",
        latin: "Suspensus Chordarum",
        painting: "El Jardín de las Delicias (Panel del Infierno)",
        realm: "infierno",
        element: "Agua",
        image: "assets/cards/card_12.jpg",
        fallbackIcon: "🎻",
        quote: "«Crucificado entre las cuerdas tensas del arpa, su cuerpo es el instrumento por donde resuena la melodía del dolor purificador.»",
        keywords: ["Entrega sagrada", "Perspectiva invertida", "Pausa forzada", "Trascendencia", "Sacrificio"],
        upright: "Necesidad de suspender la acción para contemplar la vida desde un ángulo radicalmente opuesto. Sacrificio voluntario que desata una comprensión superior. Aceptación del presente.",
        reversed: "Martirio inútil, victimismo crónico, resistencia a soltar un patrón tóxico o parálisis provocada por la culpa.",
        creature_lore: "En el Infierno Musical, los instrumentos creados para el deleite humano se transforman en aparatos de expiación: un hombre queda enredado y crucificado entre las cuerdas de un arpa monumental sobre un laúd gigante."
    },
    {
        id: 13,
        roman: "XIII",
        name: "La Muerte",
        title: "El Hombre-Árbol (Der Baummensch)",
        latin: "Arbor Humana",
        painting: "El Jardín de las Delicias / Dibujo Albertina (c. 1505)",
        realm: "infierno",
        element: "Agua",
        image: "assets/cards/card_13.jpg",
        fallbackIcon: "🪵",
        quote: "«Troncos por piernas ancladas en barcas flotantes, torso de cáscara rota donde beben los náufragos; la mirada melancólica ve nacer lo nuevo de las cenizas.»",
        keywords: ["Transformación profunda", "Fin de un ciclo", "Vaciamiento", "Metamorfosis", "Renacer"],
        upright: "Disolución inevitable de una estructura obsoleta. Muerte simbólica del ego que abre paso al renacimiento espiritual. Fin de una etapa para iniciar otra libre de lastres.",
        reversed: "Resistencia agónica a lo inevitable, estancamiento en el luto, miedo a soltar lo que ya está podrido por dentro.",
        creature_lore: "La criatura más célebre y enigmática de El Bosco: una gigantesca figura con piernas de árbol hueco sobre barcazas, cuyo cuerpo es un huevo roto con una taberna en su interior y un rostro melancólico que mira directamente al espectador."
    },
    {
        id: 14,
        roman: "XIV",
        name: "La Templanza",
        title: "El Demonio del Embudo y la Jarra",
        latin: "Temperantia Alchemica",
        painting: "Las Tentaciones de San Antonio / Tríptico de Lisboa",
        realm: "peregrinacion",
        element: "Agua",
        image: "assets/cards/card_14.jpg",
        fallbackIcon: "🏺",
        quote: "«Verte con pulso milimétrico el licor de la verdad a través del embudo de la mente, equilibrando el fuego y el rocío.»",
        keywords: ["Alquimia cotidiana", "Moderación", "Síntesis armónica", "Sanación", "Paciencia rítmica"],
        upright: "Fusión equilibrada de opuestos, sanación gradual y reintegración pacífica. Capacidad de moderar las pasiones y encontrar el punto medio donde la energía vital fluye con serenidad.",
        reversed: "Desequilibrio agudo, excesos incompatibles, mezclar elementos que se anulan o impaciencia que derrama la vasija.",
        creature_lore: "Criatura con cabeza coronada por un embudo invertido y cuerpo acorazado que manipula vasijas y retortas en las visiones antonianas, representando la transmutación de sustancias venenosas en remedios del espíritu."
    },
    {
        id: 15,
        roman: "XV",
        name: "El Diablo",
        title: "La Bestia del Caldero de Fuego",
        latin: "Diabolus Avarus",
        painting: "El Jardín de las Delicias (Panel del Infierno)",
        realm: "infierno",
        element: "Fuego",
        image: "assets/cards/card_15.jpg",
        fallbackIcon: "👹",
        quote: "«En las llamas de las calderas nocturnas, la cadena no está forjada de hierro sino de los propios anhelos inconfesables.»",
        keywords: ["Sombra instintiva", "Ataduras materiales", "Fascinación oscura", "Obsesión", "Revelación de la sombra"],
        upright: "Enfrentamiento directo con la propia sombra y los apegos inconscientes. Revelación de las cadenas autoimpuestas. Poder creativo subterráneo que debe ser reconocido para ser redimido.",
        reversed: "Liberación inminente de una adicción o apego destructivo. Ruptura de pactos tóxicos o, en su polaridad negativa, sumersión completa en el cinismo.",
        creature_lore: "Monstruos cornudos de pelaje ceniciento atienden hornazas y calderos donde el fuego de las pasiones devora la voluntad, encarnando la servidumbre del ser humano frente a sus propios apetitos desmedidos."
    },
    {
        id: 16,
        roman: "XVI",
        name: "La Torre",
        title: "La Ciudadela Gótica en Llamas",
        latin: "Turris Ignis",
        painting: "El Jardín de las Delicias (Fondo del Infierno)",
        realm: "infierno",
        element: "Fuego",
        image: "assets/cards/card_16.jpg",
        fallbackIcon: "🔥",
        quote: "«El cielo nocturno arde en azufre; las almenas del orgullo se derrumban ante el rayo de la realidad implacable.»",
        keywords: ["Colapso purificador", "Ruptura de ilusiones", "Despertar abrupto", "Catarsis", "Liberación"],
        upright: "Caída súbita pero necesaria de una estructura ilusoria que te limitaba. Revelación traumática que destruye el artificio y deja el terreno limpio para reconstruir sobre la verdad.",
        reversed: "Desastre evitado por poco, aferrarse a los escombros de una mentira conocida o temor paralizante a un colapso inminente.",
        creature_lore: "El fondo del panel infernal arde con torres góticas en silueta negra contra llamaradas y nubes de ceniza, puentes que caen y ejércitos de sombras que marchan sobre la fortaleza que creyó ser inexpugnable."
    },
    {
        id: 17,
        roman: "XVII",
        name: "La Estrella",
        title: "La Fuente Mineral del Edén",
        latin: "Fons Vitae",
        painting: "El Jardín de las Delicias (Panel del Edén)",
        realm: "eden",
        element: "Aire",
        image: "assets/cards/card_17.jpg",
        fallbackIcon: "⭐",
        quote: "«En el centro del jardín virgen surge la aguja rosada de piedra viva, manantial inagotable de aguas cristalinas y gemas.»",
        keywords: ["Esperanza radiante", "Inspiración divina", "Fe renovada", "Aguas sanadoras", "Serenidad"],
        upright: "Renovación de la fe y optimismo fundado en la armonía cósmica. Conexión con tu propósito original y manantial de inspiración límpida tras las tormentas de la prueba.",
        reversed: "Desesperanza infundada, desconexión de la propia luz interior, idealismo ingenuo que desconoce los peligros terrenales.",
        creature_lore: "La Fuente de la Vida del Edén se eleva como una portentosa aguja de coral rosa, cuarzo y alabastro orgánico sobre un estanque poblado de aves y criaturas pacíficas antes de la caída humana."
    },
    {
        id: 18,
        roman: "XVIII",
        name: "La Luna",
        title: "La Lechuza en la Oquedad de Piedra",
        latin: "Noctua Speculatrix",
        painting: "El Jardín de las Delicias (Detalle del Edén / Fuente)",
        realm: "eden",
        element: "Agua",
        image: "assets/cards/card_18.jpg",
        fallbackIcon: "🦉",
        quote: "«Desde la penumbra redonda de la cavidad mineral, los ojos fijos del ave nocturna escudriñan los enigmas que el día oculta.»",
        keywords: ["Misterio subconsciente", "Espejismo nocturno", "Sombras e intuición", "Enigma", "Sueños lúcidos"],
        upright: "Inmersión en el mundo onírico, el subconsciente y la intuición mística. Advertencia para no dejarse engañar por espejismos y aprender a ver en la más absoluta oscuridad.",
        reversed: "Confusión mental angustiosa, pesadillas, delirio o incapacidad para discernir la realidad de las sombras de la imaginación.",
        creature_lore: "La lechuza, presente de forma constante en los triptychos del Bosco, observa inmóvil desde el corazón de la Fuente de la Vida o desde huecos rocosos, como símbolo tanto de sabiduría hermética como de acechanza nocturna."
    },
    {
        id: 19,
        roman: "XIX",
        name: "El Sol",
        title: "El Huevo Primordial Germinado",
        latin: "Ovum Mundi",
        painting: "El Jardín de las Delicias (Panel Central)",
        realm: "delicias",
        element: "Fuego",
        image: "assets/cards/card_19.jpg",
        fallbackIcon: "☀️",
        quote: "«La cáscara blanquecina se quiebra para que la vida brote coronada de flores y risas al calor del mediodía.»",
        keywords: ["Claridad triunfante", "Alegría vital", "Fecundidad cósmica", "Éxito", "Luz diáfana"],
        upright: "Luz, gozo radiante, claridad absoluta de propósito y vitalidad desbordante. Los planes maduran con éxito y la verdad disipa cualquier rastro de sombra.",
        reversed: "Optimismo ciego, exceso de euforia que nubla el juicio, soberbia deslumbrada que no advierte las piedras en el camino.",
        creature_lore: "El huevo alquímico es un símbolo recurrente en el universo bosquiano: el contenedor hermético donde se gesta toda la creación viva, representando el renacer solar y la fecundidad pura del espíritu."
    },
    {
        id: 20,
        roman: "XX",
        name: "El Juicio",
        title: "Las Trompetas del Gran Despertar",
        latin: "Tuba Ultima",
        painting: "El Juicio Final (Tríptico de Viena / Brujas)",
        realm: "infierno",
        element: "Fuego",
        image: "assets/cards/card_20.jpg",
        fallbackIcon: "📯",
        quote: "«El clamor del bronce cósmico disuelve el velo del tiempo; los durmientes abren los ojos y reclaman su destino eterno.»",
        keywords: ["Despertar irrevocable", "Llamado superior", "Redención", "Transformación total", "Veredicto"],
        upright: "Llamado ineludible a una vida superior y auténtica. Liberación de viejas culpas tras un acto honesto de introspección. Renacimiento con plena lucidez moral.",
        reversed: "Sordera ante el llamado del alma, aplazamiento cobarde de una decisión crucial o autocondena injustificada.",
        creature_lore: "Ángeles trompeteros e instrumentos monumentales hacen resonar los cielos rasgados entre llamaradas y coros celestiales, donde cada alma despierta de su letargo para contemplar su verdad."
    },
    {
        id: 21,
        roman: "XXI",
        name: "El Mundo",
        title: "El Globo de la Creación Cósmica",
        latin: "Mundus Creatus",
        painting: "El Jardín de las Delicias (Tríptico Cerrado, c. 1500)",
        realm: "eden",
        element: "Éter",
        image: "assets/cards/card_21.jpg",
        fallbackIcon: "🌐",
        quote: "«La esfera cristalina suspendida en las tinieblas primigenias acoge a la tierra que amanece bajo la palabra creadora.»",
        keywords: ["Totalidad completada", "Culminación gozosa", "Integración universal", "Plenitud", "Éxito holístico"],
        upright: "Alcanzas la plenitud y la culminación de un gran ciclo de vida. Armonía entre cuerpo, mente y espíritu. El consultante se percibe como parte indivisible del cosmos.",
        reversed: "Incompletitud por temor a cerrar un capítulo, sensación de vacío a las puertas de la meta o falta de integración holística.",
        creature_lore: "Al cerrarse los postigos de El Jardín de las Delicias, aparece una sobrecogedora vista en grisalla del tercer día de la Creación: la Tierra como una esfera transparente flotando en el vacío cósmico, testimonio de la unidad divina previa a la dispersión humana."
    }
];

const BOSCH_SPREADS = [
    {
        id: "single",
        name: "El Ojo de San Antonio",
        subtitle: "Tirada Oracular de 1 Carta",
        cardCount: 1,
        description: "Inspirada en la mirada imperturbable del anacoreta frente a las visiones quiméricas. Una sola carta para recibir claridad inmediata, orientación moral o un foco de meditación diáfano.",
        icon: "👁️",
        positions: [
            {
                index: 0,
                name: "El Foco de la Visión",
                meaning: "El núcleo de tu inquietud actual, el consejo directo del bestiario y el espejo del alma ante la encrucijada."
            }
        ]
    },
    {
        id: "triptych",
        name: "El Tríptico de las Delicias",
        subtitle: "Tirada Alquímica de 3 Cartas",
        cardCount: 3,
        description: "Estructurada como las tres tablas maestras de El Bosco: el Edén Primordial, el Jardín de los Deseos y el Infierno Musical.",
        icon: "🖼️",
        positions: [
            {
                index: 0,
                name: "Tabla Izquierda: El Edén (El Pasado)",
                meaning: "El origen sagrado, las raíces inconscientes, la inocencia primordial o las semillas sembradas que dieron fruto a la situación actual."
            },
            {
                index: 1,
                name: "Tabla Central: El Jardín de las Delicias (El Presente)",
                meaning: "La realidad viva, la fascinación del deseo, los apegos mundanos, los dilemas morales y la energía que fluye en este instante."
            },
            {
                index: 2,
                name: "Tabla Derecha: El Infierno Musical (El Futuro)",
                meaning: "La cosecha kármica probable, las consecuencias de tus elecciones, la advertencia moral y la transformación purificadora."
            }
        ]
    },
    {
        id: "cross",
        name: "La Cruz Grotesca del Juicio",
        subtitle: "Tirada Mayor de 5 Cartas",
        cardCount: 5,
        description: "El oráculo mayor del bestiario: explora el alma del consultante, las tentaciones laterales, los obstáculos celestes, las raíces ocultas y la trascendencia final.",
        icon: "✝️",
        positions: [
            {
                index: 0,
                name: "El Centro: El Alma del Consultante",
                meaning: "Tu estado esencial en esta encrucijada, el punto de conciencia donde convergen todas las fuerzas."
            },
            {
                index: 1,
                name: "Flanco Izquierdo: La Tentación Seductora",
                meaning: "Lo que te atrae, el canto de sirena o la distracción del camino que pone a prueba tu templanza."
            },
            {
                index: 2,
                name: "Flanco Derecho: El Juicio y la Prueba Externa",
                meaning: "El obstáculo tangible, la espada de la justicia o la fuerza contraria que te exige madurez."
            },
            {
                index: 3,
                name: "Raíz Inferior: La Lechuza del Subconsciente",
                meaning: "Lo oculto bajo la superficie, pulsiones ancestrales, miedos soterrados o sabiduría que aún no has admitido."
            },
            {
                index: 4,
                name: "Ápice Superior: La Cúpula de Cristal (El Desenlace)",
                meaning: "La resolución trascendente, el horizonte espiritual hacia donde se dirige la situación una vez integrada la lección."
            }
        ]
    }
];
